#!/usr/bin/python

"""
Created on Tue Sep 23 13:23:11 2014
@author: chaeusler, mih
usage:
convert_behavlog_localizer.py <logfile> <outputdir>

"""


def sid2anonid(sid):
    import subprocess
    return subprocess.check_output(['../anon_id_phase2', sid]).strip()

import os
import sys

logfilename = sys.argv[1]
outdir = sys.argv[2]
task = "objectcategories"
block_stim_length = 16  # in seconds

condition_labels = ['body', 'face', 'house', 'object', 'scene', 'scramble']


def fname2sid(filename):
    test = os.path.split(filename)[1].split('_')[0]
    return test


def log2data(fname):
    """Parse logfile and extract relevant data

    Parameters
    ----------
    fname : str
      Log file name

    Returns
    -------
    list
      Each item is a list with the relevant fields from the relevant lines.
    """
    out = []
    for line in open(fname, 'r'):
        seq = line.split()
        if len(seq) < 3 or not seq[2].startswith('MYLOG:'):
            continue
        out.append((seq[0], seq[4], seq[5]))

    return out


def write_onsets(onsets, outdir, anonid, run, task):
    fname = os.path.join(
        outdir, anonid, 'ses-localizer', 'func',
        '%s_ses-localizer_task-%s_run-%i_events.tsv'
        % (anonid, task, run))
    path = os.path.dirname(fname)
    if not os.path.exists(path):
        os.makedirs(path)
    import csv
    with open(fname, 'w') as csvfile:
        writer = csv.writer(
            csvfile, delimiter='\t',
            quotechar='"', quoting=csv.QUOTE_MINIMAL)
        writer.writerow(['onset', 'duration', 'trial_type'])
        for cond, onset in onsets:
            writer.writerow(["%.3f" % onset, 16, cond])


def generate_output(data, outdir, anonid, task):
    run_counter = 0
    block_counter = 0
    run_begin = 0.0
    onsets = None

    for line in data:
        if line[1] == 'RUN':
            if not onsets is None:
                write_onsets(onsets, outdir, anonid, run_counter, task)
            run_begin = float(line[0])
            run_counter += 1
            onsets = []
        elif line[1] == 'BLOCK':
            cond = line[2]
            onsets.append((cond, float(line[0]) - run_begin))
            block_counter += 1
        else:
            raise RuntimeError("I am not possible")
    write_onsets(onsets, outdir, anonid, run_counter, task)


##############################
##############################
##############################

data = log2data(logfilename)
sid = fname2sid(logfilename)
anonid = sid2anonid(sid)
generate_output(data, outdir, anonid, task)
