#!/bin/bash
# Run in root of the anondata. It find the BOLD files for task004 and places
# the matching onset files into the right location. All cmdline magic.
# Uses model002 for export

for f in $(ls -1 */BOLD/task004_run001/bold.nii.gz | sed -e 's,BOLD,model/model002/onsets,' -e 's/bold.nii.gz/cond001.txt/' | tr @ ' '); do
    mkdir -p $(dirname $f)
    echo "Create $f"
    cat << EOT > $f
0.0	12.0	1.0
24.0	12.0	1.0
48.0	12.0	1.0
72.0	12.0	1.0
EOT
done
