#!/bin/bash
#
# Synopsis:
#
#  convert_dicoms_phase2_movie <p1 tarball> <p2 tarball> <outdir>
#
# Converts DICOMs from
#
# requires 'numbound' from num-utils'

set -e
set -u

. /etc/fsl/fsl.sh
. code/rawdata_conversion/libdeface.sh

get_latest_file () {
   echo $(find "$1" -name "$2" | sort | tail -n1)
}

proc_fmri_bundle () {
  tbn="$1"
  destdir="$2"
  subj="$3"
  type="$4"
  task="$5"
  run="$6"
  initmat="$7"
  realign="$8"
  sr="${9}"
  basedir="$destdir/$type/"
  basename="sub-${subj}_ses-movie_task-${task}_run-${run}"
  mkdir -p "$basedir"
  inbase="${tbn%*.nii}"
  getdeface ${inbase}.nii "${initmat}" ${inbase} "$realign" "$sr"
  export_defaced ${inbase} instd $basedir/${basename}_bold $basedir/${basename}_defacemask
  # beautify the image header based on protocol info (all hard coded)
  python -c "import nibabel as nb; img=nb.load(\"${basedir}/${basename}_bold.nii.gz\"); hdr=img.get_header(); hdr.set_dim_info(freq=0, phase=1, slice=2); hdr['slice_code'] = nb.nifti1.slice_order_codes['sequential increasing']; hdr.set_intent('time series', name='time series'); hdr.set_xyzt_units(xyz='mm', t='sec'); hdr.set_slice_duration(hdr['pixdim'][4]/hdr.get_n_slices()); hdr['slice_start']=0; hdr['slice_end']=34; hdr['cal_min']=img.get_data().min(); hdr['cal_max']=img.get_data().max(); hdr['descrip']='FOV=[240,240,115.2];SENSE=2;TE=30;flipangle=90;fatshift=12.5px;CLEAR=y'; hdr['aux_file']=''; img.to_filename(\"${basedir}/${basename}_bold.nii.gz\")"
}
###############################################################################
###############################################################################
###############################################################################

subj="$(basename $1 | cut -f 1,1 -d _)"
anon_id="$(../anon_id $subj)"
anon_id=${anon_id:1:3}
outdir=$(readlink -f "$3")
dcmsrc="$(for src in $(ls -1 $1 $2 | sort |tail -n2); do readlink -f $src ; done)"
niitmpdir='nii'
curdir="$(pwd)"
destdir="$outdir/sub-$anon_id/ses-movie"
wdir=$(mktemp -d)
mkdir -p "$wdir"
convcall="dcm2niix -o ${niitmpdir}"

cd $wdir
echo "Work directory: $(pwd)"
# extract dicoms
for dcm in ${dcmsrc}; do
	echo "Unpack"
	tar -xf ${dcm}
	dcmdir="$(find . -mindepth 1 -type d)/"

	mkdir -p ${niitmpdir}
	$convcall ${dcmdir}
	srcdir="${wdir}/${niitmpdir}"

	firstrun=1
	## derive initial transform from scratch -- afterwards go incremental
	for run in $(ls -1 ${srcdir}/*3mm_R*nii* | sed -e 's/.*3mm_R//' -e 's/_SENSE.*//' | sort| uniq); do
		if [ $firstrun -eq 1 ]; then
			proc_fmri_bundle "$(get_latest_file "${srcdir}" "*3mm_R${run}*.nii*")" $destdir $anon_id functional movie ${run} '' 1 90
		else
			proc_fmri_bundle "$(get_latest_file "${srcdir}" "*3mm_R${run}*.nii*")" $destdir $anon_id functional movie ${run} "${srcdir}/*3mm_R$((${run} - 1))*.mat" 1 10
		fi
		firstrun=0
	done
	rm -rf ./*
	ls -l
done
# orderly exit
rm -rf $wdir
