#!/bin/bash

# This shell script:
#- needs to run from the root of the dataset;
#- takes as input an eye tracker compressed ascii (.asc.gz) file;
#- gets the anonymised ID;
#- cuts the first two lines of the original file;
#- writes down a anonimised file into the anonymization directory using the anonimised filename.
# - prints a line on the std_out with anonymised ID and run

# Usage:
# ./convert_eyetracker_av /path/to/filename.asc.gz

# Parse relevant information from original filename
in_file="$(readlink -f $1)"
raw_original_name=$(basename $1)
original_id=${raw_original_name:0:4}
the_run=${raw_original_name:7:1}

# Extract the anonymised ID
the_anon_id=$(../anon_id $original_id)
the_anon_id=${the_anon_id:1:2}

# Creates the target directory according to anonimised information
mkdir -p sub-${the_anon_id}/ses-movie/func

# Cut the first two lines of the file and redirect the output into a new file in the target directory
zcat ${in_file} | tail -n +3 > sub-${the_anon_id}/ses-movie/func/sub-${the_anon_id}_ses-movie_task-movie_run-${the_run}_eyelinkraw.asc
