#!/bin/bash
#
set -e
set -u

# anatomical session
cat scripts/condor/export_anatomical_session.in > scripts/condor/export_anatomical_session
for sid in $(anon_id list); do
  printf "arguments = $sid $(anon_id $sid)\nqueue 1\n" >> scripts/condor/export_anatomical_session
done
condor_submit scripts/condor/export_anatomical_session
rm scripts/condor/export_anatomical_session

# physio data
cat scripts/condor/export_7Tad_physio.in > scripts/condor/export_7Tad_physio
for sid in $(anon_id list); do
  printf "arguments = 7T_ad/data/$sid/raw/physio openfmri.org/sub$(anon_id $sid)/physio/task001 conversion.log\nqueue 1\n" >> scripts/condor/export_7Tad_physio
done
condor_submit scripts/condor/export_7Tad_physio
rm scripts/condor/export_7Tad_physio

# functional session
cat scripts/condor/export_functional_session.in > scripts/condor/export_functional_session
for sid in $(anon_id list); do
  printf "arguments = $sid $(anon_id $sid)\nqueue 1\n" >> scripts/condor/export_functional_session
done
condor_submit scripts/condor/export_functional_session
rm scripts/condor/export_functional_session

# angio data
cat scripts/condor/export_angio_session.in > scripts/condor/export_angio_session
for sid in $(anon_id list); do
  printf "arguments = $sid $(anon_id $sid)\nqueue 1\n" >> scripts/condor/export_angio_session
done
condor_submit scripts/condor/export_angio_session
rm scripts/condor/export_angio_session



