#!/usr/bin/python

import sys
import csv
import numpy as np
from mvpa2.misc.plot import plot_bars
import pylab as pl

if not len(sys.argv) == 3:
    print "Call with <data.csv> <output.svg>"
    sys.exit(1)

data = []
for i, row in enumerate(csv.reader(open(sys.argv[1]))):
    if i == 0:
        continue
    data.append([int(v) for v in row[-8:]])

data = np.array(data)
pl.figure(figsize=(4,4))
plot_bars(data.T, ylim=(1,4), xloc=np.arange(1,9)-0.25, width=0.5, alpha=1)
#pl.boxplot(data, notch=1)
pl.xlim((0.2, 8.8))
pl.xlabel('Movie segment')
#pl.ylabel('Rating (scale: 1-4)')
pl.yticks(range(1,5), ('very\npoor', 'rather\npoor', 'rather\ngood', 'very\ngood'),
          rotation=0, horizontalalignment='right', stretch='condensed',
          verticalalignment='center', multialignment='center')
pl.title('Subjective acoustic quality')
for i in (2,3):
    pl.axhline(i, linestyle='-', color='0.4', alpha=.5, zorder=-1)
for i in (1.5, 2.5, 3.5):
    pl.axhline(i, linestyle='--', color='0.6', alpha=.5, zorder=-1)
pl.savefig(sys.argv[2])
